---
- name: Create Deluge Directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ deluge_config_directory }}"
    - "{{ deluge_download_directory }}"

- name: Deluge Docker Container
  community.docker.docker_container:
    name: deluge
    image: linuxserver/deluge
    pull: true
    volumes:
      - "{{ deluge_config_directory }}:/config:rw"
      - "{{ deluge_download_directory }}:/downloads:rw"
    ports:
      - "{{ deluge_port }}:8112"
      - "{{ deluge_incomming_port }}:62987"
    env:
      TZ: "{{ deluge_timezone }}"
      PUID: "{{ deluge_user_id }}"
      PGID: "{{ deluge_group_id }}"
    restart_policy: unless-stopped
    memory: "{{ deluge_memory }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.deluge.rule: "Host(`{{ deluge_hostname }}.{{ domain }}`)"
      traefik.http.routers.deluge.tls.certresolver: "letsencrypt"
      traefik.http.routers.deluge.tls.domains[0].main: "{{ domain }}"
      traefik.http.routers.deluge.tls.domains[0].sans: "*.{{ domain }}"
      traefik.http.services.deluge.loadbalancer.server.port: "8112"
