---
- name: Create cloudflare Dynamic DNS Directories
  ansible.builtin.file:
    path: "{{ cloudflare_data_directory }}"
    mode: "700"
    state: directory

- name: Template Cloudflare Dynamic DNS config.yml with scoped token
  ansible.builtin.template:
    src: config.yml
    dest: "{{ cloudflare_data_directory }}/config.yml"
    mode: "664"
  register: template_files_result

- name: Cloudflare Dynamic DNS Container
  community.docker.docker_container:
    name: "{{ cloudflare_container_name }}"
    image: joshava/cloudflare-ddns:latest
    pull: true
    volumes:
      - "{{ cloudflare_data_directory }}/config.yml:/app/config.yaml"
    restart_policy: unless-stopped
    memory: "{{ cloudflare_memory }}"
    recreate: "{{ template_files_result is changed }}"

