---
# directories
deluge_config_directory: "{{ docker_home }}/deluge/config"
deluge_download_directory: "{{ downloads_root }}"
deluge_watch_directory: "{{ torrents_root }}"

# uid / gid
deluge_user_id: "0"
deluge_group_id: "0"

# error logging
deluge_log_level: "error"

# network
deluge_port: "8112"
deluge_hostname: "deluge"
deluge_incomming_port: "62987"

deluge_timezone: "{{ timezone }}"

# specs
deluge_memory: 1g

deluge_container_name: deluge
deluge_whitelist_ips: 0.0.0.0/0