---
- name: Create Bazarr Directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ bazarr_data_directory }}"

- name: Bazarr
  community.docker.docker_container:
    name: "{{ bazarr_container_name }}"
    image: linuxserver/bazarr
    pull: true
    volumes:
      - "{{ bazarr_media_directory }}:/media:rw"
      - "{{ bazarr_data_directory }}:/config:rw"
    ports:
      - "{{ bazarr_port }}:6767"
    env:
      TZ: "{{ timezone }}"
      PUID: "{{ bazarr_user_id }}"
      PGID: "{{ bazarr_group_id }}"
    restart_policy: unless-stopped
    memory: "{{ bazarr_memory }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.bazarr.rule: "Host(`{{ bazarr_hostname }}.{{ domain }}`)"
      traefik.http.routers.bazarr.tls.certresolver: "letsencrypt"
      traefik.http.routers.bazarr.tls.domains[0].main: "{{ domain }}"
      traefik.http.routers.bazarr.tls.domains[0].sans: "*.{{ domain }}"
      traefik.http.services.bazarr.loadbalancer.server.port: "6767"
      traefik.http.routers.bazarr.middlewares: "bazarr_whitelist_middleware@docker"
      traefik.http.middlewares.bazarr_whitelist_middleware.ipwhitelist.sourcerange: "{{ bazarr_whitelist_ips }}"